INSERT INTO "public"."g2p_attribute_values" ("value_id","attribute_id","value_code","value_display","parent_value_id","sort_order") VALUES
('LVH_AGRICULTURE','PRIMARY_LIVELIHOOD','AGRICULTURE','Agriculture, Forestry and Fishing',NULL,1),
('LVH_LIVESTOCK','PRIMARY_LIVELIHOOD','LIVESTOCK','Livestock Rearing',NULL,2),
('LVH_CRAFT','PRIMARY_LIVELIHOOD','CRAFT','Craft and Related Trades',NULL,3),
('LVH_SERVICES','PRIMARY_LIVELIHOOD','SERVICES','Services and Sales',NULL,4),
('LVH_WAGE_LABOUR','PRIMARY_LIVELIHOOD','WAGE_LABOUR','Casual Wage Labour',NULL,5),
('LVH_PETTY_TRADE','PRIMARY_LIVELIHOOD','PETTY_TRADE','Petty Trading',NULL,6),
('LVH_GOVT_EMPLOYMENT','PRIMARY_LIVELIHOOD','GOVT_EMPLOYMENT','Government Employment',NULL,7),
('LVH_UNEMPLOYED','PRIMARY_LIVELIHOOD','UNEMPLOYED','Unemployed / No Livelihood',NULL,8),
('LVH_OTHER','PRIMARY_LIVELIHOOD','OTHER','Other',NULL,9),
('CS_REDUCE_MEALS','COPING_STRATEGY','REDUCE_MEALS','Reduce number or size of meals',NULL,1),
('CS_BORROW','COPING_STRATEGY','BORROW','Borrow from family/friends',NULL,2),
('CS_SELL_ASSETS','COPING_STRATEGY','SELL_ASSETS','Sell productive assets',NULL,3),
('CS_MIGRATE','COPING_STRATEGY','MIGRATE','Migrate for work',NULL,4),
('CS_WITHDRAW_SCHOOL','COPING_STRATEGY','WITHDRAW_SCHOOL','Withdraw children from school',NULL,5),
('CS_SEEK_AID','COPING_STRATEGY','SEEK_AID','Seek emergency aid',NULL,6),
('CS_NONE','COPING_STRATEGY','NONE','No coping strategy',NULL,7),
('DS_SELF_REPORT','DATA_SOURCE','SELF_REPORT','Self-report',NULL,1),
('DS_FIELD_VERIFICATION','DATA_SOURCE','FIELD_VERIFICATION','Field verification',NULL,2),
('DS_PROGRAMME_MIS','DATA_SOURCE','PROGRAMME_MIS','Programme MIS integration',NULL,3),
('DS_FOUNDATIONAL_ID','DATA_SOURCE','FOUNDATIONAL_ID','Foundational ID API',NULL,4),
('DS_COMMUNITY_VALIDATION','DATA_SOURCE','COMMUNITY_VALIDATION','Community validation',NULL,5)
ON CONFLICT (attribute_id, value_id) DO NOTHING;
